### ISSUE TITLE
Twitter handle

### ISSUE THREAD

**Issue by keunes** [ferdium/branding#3]
Hi folks,

Thank you so much to everyone involved in this fork! I just wanted to chime in on Discord but the invite link doesn't work for me. Either way, I wanted to let you folks know that, once (an initial version of) the website is up, you might want to try to get the twitter handle `@ferdium`. The current user holding this handle has created the account in 2014 has posted 1 tweet.

A couple of years back I was in a similar situation with a volunteer organisation and I managed to get the desired account. So I would definitely give it a shot :)

This form can be used: https://help.twitter.com/en/forms/authenticity/impersonation/my-company-brand-or-org

Happy to help out

Cheers

**Comment by dqos** [comment]
Hi,

We are currently using @ferdiumteam 😄
